# Generated by Django 2.2.1 on 2019-05-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='lifes.Photo')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='professions.Profession')),
            ],
        ),
    ]
