# Generated by Django 2.2.1 on 2019-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=1000)),
                ('discovery', models.TextField(max_length=10000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
